
package turismoservidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-19T18:00:59.008-03:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "ActividadRepetidaException", targetNamespace = "http://publicador/")
public class ActividadRepetidaException_Exception extends Exception {

    private ActividadRepetidaException faultInfo;

    public ActividadRepetidaException_Exception() {
        super();
    }

    public ActividadRepetidaException_Exception(String message) {
        super(message);
    }

    public ActividadRepetidaException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ActividadRepetidaException_Exception(String message, ActividadRepetidaException actividadRepetidaException) {
        super(message);
        this.faultInfo = actividadRepetidaException;
    }

    public ActividadRepetidaException_Exception(String message, ActividadRepetidaException actividadRepetidaException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = actividadRepetidaException;
    }

    public ActividadRepetidaException getFaultInfo() {
        return this.faultInfo;
    }
}
