
package turismoservidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-20T13:40:54.571-03:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "ActividadNoExisteException", targetNamespace = "http://publicador/")
public class ActividadNoExisteException_Exception extends Exception {

    private ActividadNoExisteException faultInfo;

    public ActividadNoExisteException_Exception() {
        super();
    }

    public ActividadNoExisteException_Exception(String message) {
        super(message);
    }

    public ActividadNoExisteException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ActividadNoExisteException_Exception(String message, ActividadNoExisteException actividadNoExisteException) {
        super(message);
        this.faultInfo = actividadNoExisteException;
    }

    public ActividadNoExisteException_Exception(String message, ActividadNoExisteException actividadNoExisteException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = actividadNoExisteException;
    }

    public ActividadNoExisteException getFaultInfo() {
        return this.faultInfo;
    }
}
