
package turismoservidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-19T18:00:58.993-03:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "UsuarioRepetidoException", targetNamespace = "http://publicador/")
public class UsuarioRepetidoException_Exception extends Exception {

    private UsuarioRepetidoException faultInfo;

    public UsuarioRepetidoException_Exception() {
        super();
    }

    public UsuarioRepetidoException_Exception(String message) {
        super(message);
    }

    public UsuarioRepetidoException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UsuarioRepetidoException_Exception(String message, UsuarioRepetidoException usuarioRepetidoException) {
        super(message);
        this.faultInfo = usuarioRepetidoException;
    }

    public UsuarioRepetidoException_Exception(String message, UsuarioRepetidoException usuarioRepetidoException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = usuarioRepetidoException;
    }

    public UsuarioRepetidoException getFaultInfo() {
        return this.faultInfo;
    }
}
