
package turismoservidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-20T13:40:54.565-03:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "UsuarioNoExisteException", targetNamespace = "http://publicador/")
public class UsuarioNoExisteException_Exception extends Exception {

    private UsuarioNoExisteException faultInfo;

    public UsuarioNoExisteException_Exception() {
        super();
    }

    public UsuarioNoExisteException_Exception(String message) {
        super(message);
    }

    public UsuarioNoExisteException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UsuarioNoExisteException_Exception(String message, UsuarioNoExisteException usuarioNoExisteException) {
        super(message);
        this.faultInfo = usuarioNoExisteException;
    }

    public UsuarioNoExisteException_Exception(String message, UsuarioNoExisteException usuarioNoExisteException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = usuarioNoExisteException;
    }

    public UsuarioNoExisteException getFaultInfo() {
        return this.faultInfo;
    }
}
