package publicador;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-19T15:29:24.905-03:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://publicador/", name = "Publicador")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Publicador {

    @WebMethod
    @Action(input = "http://publicador/Publicador/crearDeportistaRequest", output = "http://publicador/Publicador/crearDeportistaResponse", fault = {@FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://publicador/Publicador/crearDeportista/Fault/UsuarioRepetidoException")})
    public void crearDeportista(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        java.lang.String arg3,
        @WebParam(partName = "arg4", name = "arg4")
        javax.xml.datatype.XMLGregorianCalendar arg4,
        @WebParam(partName = "arg5", name = "arg5")
        boolean arg5,
        @WebParam(partName = "arg6", name = "arg6")
        java.lang.String arg6,
        @WebParam(partName = "arg7", name = "arg7")
        boolean arg7
    ) throws UsuarioRepetidoException_Exception;

    @WebMethod
    @Action(input = "http://publicador/Publicador/crearEntrenadorRequest", output = "http://publicador/Publicador/crearEntrenadorResponse", fault = {@FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://publicador/Publicador/crearEntrenador/Fault/UsuarioRepetidoException")})
    public void crearEntrenador(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        java.lang.String arg3,
        @WebParam(partName = "arg4", name = "arg4")
        javax.xml.datatype.XMLGregorianCalendar arg4,
        @WebParam(partName = "arg5", name = "arg5")
        boolean arg5,
        @WebParam(partName = "arg6", name = "arg6")
        java.lang.String arg6,
        @WebParam(partName = "arg7", name = "arg7")
        java.lang.String arg7,
        @WebParam(partName = "arg8", name = "arg8")
        java.lang.String arg8
    ) throws UsuarioRepetidoException_Exception;
}
