
package turismoservidor;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://turismoservidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns turismoservidor.DataUsuario
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://turismoservidor/WebServices/verInfoUsuarioRequest", output = "http://turismoservidor/WebServices/verInfoUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://turismoservidor/WebServices/verInfoUsuario/Fault/UsuarioNoExisteException")
    })
    public DataUsuario verInfoUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://turismoservidor/WebServices/registrarUsuarioRequest", output = "http://turismoservidor/WebServices/registrarUsuarioResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://turismoservidor/WebServices/registrarUsuario/Fault/UsuarioRepetidoException")
    })
    public void registrarUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        DataUsuario arg0)
        throws UsuarioRepetidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns turismoservidor.DataListaSalidas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://turismoservidor/WebServices/cargarSalidasPersistenciaRequest", output = "http://turismoservidor/WebServices/cargarSalidasPersistenciaResponse")
    public DataListaSalidas cargarSalidasPersistencia(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns turismoservidor.DataListaActividades
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://turismoservidor/WebServices/getActividadesPersistenciaRequest", output = "http://turismoservidor/WebServices/getActividadesPersistenciaResponse")
    public DataListaActividades getActividadesPersistencia();

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns turismoservidor.DataSalida
     * @throws SalidaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://turismoservidor/WebServices/verInfoSalidaRequest", output = "http://turismoservidor/WebServices/verInfoSalidaResponse", fault = {
        @FaultAction(className = SalidaNoExisteException_Exception.class, value = "http://turismoservidor/WebServices/verInfoSalida/Fault/SalidaNoExisteException")
    })
    public DataSalida verInfoSalida(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws SalidaNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws ActividadRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://turismoservidor/WebServices/registrarActividadRequest", output = "http://turismoservidor/WebServices/registrarActividadResponse", fault = {
        @FaultAction(className = ActividadRepetidaException_Exception.class, value = "http://turismoservidor/WebServices/registrarActividad/Fault/ActividadRepetidaException")
    })
    public void registrarActividad(
        @WebParam(name = "arg0", partName = "arg0")
        DataActividad arg0)
        throws ActividadRepetidaException_Exception
    ;

}
